api_platform:
    version: 0.1.0
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    oauth:
        # To enable or disable OAuth.
        enabled: true

        # The OAuth client ID.
        clientId: 'documentation_client'

        # The OAuth client secret.
        clientSecret: 'documentation_client_secret'

        # The OAuth type.
        type: 'oauth2'

        # The OAuth flow grant type.
        flow: 'authorizationCode'

        # The OAuth token URL.
        tokenUrl: 'https://127.0.0.1:8000/accounts/token'

        # The OAuth authentication URL.
        authorizationUrl: 'https://127.0.0.1:8000/accounts/authorize'

        # The OAuth scopes.
        scopes:
            USER_WRITE: USER_WRITE
            POST_CREATE: POST_CREATE
            POST_WRITE: POST_WRITE
            POST_DELETE: POST_DELETE
    graphql:
        # Enabled by default with installed webonyx/graphql-php.
        enabled: false

        # The default IDE (graphiql or graphql-playground) used when going to the GraphQL endpoint. False to disable.
        default_ide: 'graphql_playground'

        graphiql:
            # Enabled by default with installed webonyx/graphql-php and Twig.
            enabled: false

        graphql_playground:
            # Enabled by default with installed webonyx/graphql-php and Twig.
            enabled: false

        # The nesting separator used in the filter names.
        nesting_separator: _

        collection:
            pagination:
                enabled: true

when@prod:
    api_platform:
        oauth:
            tokenUrl: 'https://accounts.%domain%/token'

                # The OAuth authentication URL.
            authorizationUrl: 'https://accounts.%domain%/authorize'
