#controllers:
#    resource: ../../src/Controller/
#    exclude: ../../src/Controller/Account
#    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation


account:
    name_prefix: app_account_
    resource: ../../src/Controller/Account
    type: annotation
    prefix: /accounts


when@prod:
    account:
        name_prefix: app_account_
        resource: ../../src/Controller/Account
        type: annotation
        host: 'accounts.%domain%'
        prefix: /
