nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'append', 'delete', 'entries', 'foreach', 'get', 'has', 'keys', 'set', 'values']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            origin_regex: false
            allow_origin:  ['*']
            allow_headers: ['*']
            allow_methods: ['*']
            max_age: 86400
            hosts: ['^api\.']
        '^/token':
            origin_regex: false
            allow_origin: ['*']
            allow_methods: ['POST']
            hosts: ['^accounts\.']
        '^\/':
            origin_regex: false
            allow_origin: []
            hosts: ['^accounts\.']
